vich_uploader:
    db_driver: orm

    mappings:
        word_image:
            uri_prefix: /images/word
            upload_destination: '%kernel.project_dir%/public/images/word'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        audio_serie:
            uri_prefix: /audios/serie
            upload_destination: '%kernel.project_dir%/public/audios/serie'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true